export enum Phase {
    LOBBY = "LOBBY",
    ROLE_SELECTION = "ROLE_SELECTION",
    DISTRIBUTION = "DISTRIBUTION",
    NIGHT = "NIGHT",
    SHERIFF_ELECTION = "SHERIFF_ELECTION",
    DAY = "DAY",
    GAME_OVER = "GAME_OVER"
}